### ISSUE TITLE
Cloudformation stack references old AMI

### ISSUE THREAD

**Issue by tg-wpittman** [aws-quickstart/quickstart-aviatrix-controller#24]
The cloudformation stack that handles the launch of the controller references a deprecated AMI image. This prevents the stack from successfully launching.

From Cloudformation console: 

```API: ec2:RunInstances Not authorized for images: [ami-0457f4f81db29f339]```

This was attempting to launch in the us-east-2(Ohio) region.

**Comment by tg-wpittman** [comment]
I have attempted to launch the stack in us-east-1 and received a similar message. 

```API: ec2:RunInstances Not authorized for images: [ami-0c558f64af58868d9]```

Our team is really wanting to set if this product is a good fit for our project, but with not even being able to get the stack stood up we are simply unable to test it out.

**Comment by sshvans** [comment]
@tg-wpittman Based on the message, it seems that your AWS account is doesn't have permissions to use the AMI. Have you followed the instructions in the [Quick Start deployment guide](https://aws.amazon.com/quickstart/architecture/aviatrix-global-transit-hub/) and subscribed to the AMI from AWS Marketplace?

**Comment by tg-wpittman** [comment]
Yes - I have followed the documentation and I am able to launch the EC2 instance on its own. When I do launch the EC2, the AMI ID of the instance is not the same as the AMI ID referenced in the cloudformation template. 

The documentation I have found for the error ```API: ec2:RunInstances Not authorized for images``` point towards the referenced AMI being deprecated:

https://stackoverflow.com/questions/22653307/aws-ami-deprecation-api-ec2runinstances-not-authorized-for-images

https://github.com/aws-quickstart/quickstart-microsoft-exchange/issues/17

https://acloud.guru/forums/aws-cda-2018/discussion/-LdIIHfYbnqJmu3hwoi4/unable

https://forums.aws.amazon.com/thread.jspa?messageID=530199

**Comment by sshvans** [comment]
@tg-wpittman It does seems like Aviatrix has released new AMIs. I have reached out to them to confirm the latest AMIs. Will update this issue once I hear back.

**Comment by SamGforce** [comment]
Hi Folks, We are in process of updating this. Stay tuned.

**Comment by tg-wpittman** [comment]
It looks like the official Aviatrix controller CF template is using AMI IDs that were updated in August:  https://github.com/AviatrixSystems/aws-controller-launch-cloudformation-templates/pull/33/files

**Comment by sshvans** [comment]
This has been fixed in the pr #25
